### ISSUE TITLE
stderr maxBuffer exceeded

### ISSUE THREAD

**Issue by codebykenny** [damianociarla/node-ffmpeg#35]
```
Error encoding file:  { Error: stderr maxBuffer exceeded
    at Socket.onChildStderr (child_process.js:283:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
  cmd: 'ffmpeg -i "video.avi" -preset veryfast -crf 18 -c:a libfdk_aac -b:a 128k -f mp4 "video.mp4"' }
```

It appears 200 KB is not a big enough maxBuffer when coding avi -> mp4

**Comment by damianociarla** [comment]
Fixed in 1.0.0. The retained output limit is now 16 MiB by default and behaves as a tail buffer: reaching maxBuffer no longer terminates FFmpeg. The value remains configurable per call.
