### ISSUE TITLE
Can I use ffmpeg-static?

### ISSUE THREAD

**Issue by haojia321** [damianociarla/node-ffmpeg#45]
Hi,
If I use this package on my cloud server(which may not have ffmpeg installed on the linux server), so can I use ffmpeg-static instead? Something like this: https://www.npmjs.com/package/ffmpeg-static

**Comment by Aspvik** [comment]
Did you figure it out?

**Comment by gavinwilliams** [comment]
This works fine with `ffmpeg-static`. You just need to set `ffmpeg.bin` to `ffmpeg-static.path` like the below in ES6.

```
import ffmpeg_static from 'ffmpeg-static'
import ffmpeg from 'ffmpeg'
ffmpeg.bin = ffmpeg_static.path
```

From here, you're free to use ffmpeg however you like.

**Comment by jens1o** [comment]
@yaphper You need to install ffmpeg(the binary itself) before using a wrapper that eases making commands to ffmpeg.

**Comment by haojia321** [comment]
@jens1o I cannot manage the cloud server so I cannot manually install anything on the server. when you say "ffmpeg binary", you mean i need to manually install it on the server, right?

**Comment by haojia321** [comment]
I got this error:

W20190221-00:21:07.641(-5)? (STDERR) fs.js:948
W20190221-00:21:07.642(-5)? (STDERR)   binding.stat(pathModule._makeLong(path));
W20190221-00:21:07.642(-5)? (STDERR)           ^
W20190221-00:21:07.642(-5)? (STDERR) 
W20190221-00:21:07.642(-5)? (STDERR) TypeError: path must be a string or Buffer
W20190221-00:21:07.642(-5)? (STDERR)     at Object.fs.statSync (fs.js:948:11)
W20190221-00:21:07.643(-5)? (STDERR)     at Object.statSync (/Users/i839603/eduees/code/prototypes/videoprocessor/node_modules/graceful-fs/polyfills.js:297:22)
W20190221-00:21:07.643(-5)? (STDERR)     at server/main.js:61:60
W20190221-00:21:07.643(-5)? (STDERR)     at /Users/i839603/eduees/code/prototypes/videoprocessor/node_modules/ffmpeg/lib/video.js:583:5
W20190221-00:21:07.643(-5)? (STDERR)     at /Users/i839603/eduees/code/prototypes/videoprocessor/node_modules/ffmpeg/lib/utils.js:20:3
W20190221-00:21:07.643(-5)? (STDERR)     at ChildProcess.exithandler (child_process.js:282:5)
W20190221-00:21:07.643(-5)? (STDERR)     at emitTwo (events.js:126:13)
W20190221-00:21:07.644(-5)? (STDERR)     at ChildProcess.emit (events.js:214:7)
W20190221-00:21:07.644(-5)? (STDERR)     at maybeClose (internal/child_process.js:925:16)
W20190221-00:21:07.644(-5)? (STDERR)     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by jens1o** [comment]
> you mean i need to manually install it on the server, right?

yeah. This is just a wrapper to make you more comfortable writing ffmpeg commands.

**Comment by haojia321** [comment]
@jens1o do you know if there is any package that doesnt need manually install ffmpeg on the server? The cloud im using doesnt allow install software.

**Comment by jens1o** [comment]
Nope. Hosting the stuff yourself isn't an option, which would also benefit user privacy?

**Comment by Zaphiruz** [comment]
Had the same issue. [video.js](https://github.com/damianociarla/node-ffmpeg/blob/master/lib/video.js#L559) still has a hardcoded `'ffmpeg'`

**Comment by kodie** [comment]
Just in case anyone else runs into this, I have made a fork that makes the ffmpeg executable configurable: #88

**Comment by morgan-wild** [comment]
UP! ^^

**Comment by damianociarla** [comment]
Supported in 1.0.0. Set ffmpeg.bin and ffmpeg.ffprobeBin to paths supplied by ffmpeg-static/ffprobe-static, or pass ffmpegPath and ffprobePath per call. All presets now honor these paths. Documentation: https://damianociarla.github.io/node-ffmpeg/guide/configuration
