### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by gauri08** [damianociarla/node-ffmpeg#61]
I am trying to add watermark to video but it failed.
Error is:

error:  { Error: Command failed: ffmpeg -i assets/encoded/upload-157113597459120191009_171749.mp4 -i assets/logo/logo.png  -filter_complex "overlay=0-0+0:main_h-overlay_h-0+0" assets/encoded/water-157113597459120191009_171749.mp4
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:188:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'ffmpeg -i assets/encoded/upload-157113597459120191009_171749.mp4 -i assets/logo/logo.png  -filter_complex "overlay=0-0+0:main_h-overlay_h-0+0" assets/encoded/water-157113597459120191009_171749.mp4' }

Please help me !

**Comment by lida1984** [comment]
To use this library requires that ffmpeg is already installed

**Comment by gauri08** [comment]
ffmpeg is already installed.
It gives error for some videos.

**Comment by lida1984** [comment]
It may be your ffmpeg has a fail position.

**Comment by lida1984** [comment]
You must be sure your ffmpeg has a best position to your code file

**Comment by lida1984** [comment]
You must be sure your ffmpeg has a best relative path to your code file

**Comment by gauri08** [comment]
Sorry, I didn't get

**Comment by gauri08** [comment]
It gives  Invalid data found when processing input

**Comment by damianociarla** [comment]
Version 1.0.0 reports missing executables clearly and supports ffmpegPath/ffprobePath per call as well as ffmpeg.bin/ffprobeBin globally. The original 'ffmpeg is not recognized' message means the executable was not available on PATH for that process. Configuration: https://damianociarla.github.io/node-ffmpeg/guide/configuration
